# Generated by Django 6.0 on 2026-01-04 11:12

import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, "Column name cannot be empty."
                            ),
                            django.core.validators.MaxLengthValidator(
                                50, "Column name cannot exceed 50 characters."
                            ),
                            core.validators.validate_no_special_chars,
                        ],
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Position cannot be negative."
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="boards.board",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "indexes": [
                    models.Index(
                        fields=["board", "position"],
                        name="columns_col_board_i_699851_idx",
                    )
                ],
                "unique_together": {("board", "name")},
            },
        ),
    ]
