# Generated by Django 6.0 on 2026-01-04 10:47

import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, "Board name cannot be empty."
                            ),
                            django.core.validators.MaxLengthValidator(
                                100, "Board name cannot exceed 100 characters."
                            ),
                            core.validators.validate_no_special_chars,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        validators=[
                            django.core.validators.MaxLengthValidator(
                                500, "Description cannot exceed 500 characters."
                            )
                        ],
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "is_archived"],
                        name="boards_boar_owner_i_bd48ab_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="boards_boar_created_878824_idx"
                    ),
                ],
            },
        ),
    ]
