apiVersion: v1
kind: Secret
metadata:
  name: kanban-secrets
  namespace: kanban-thunder
  labels:
    app.kubernetes.io/name: kanban-thunder
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-k8s-prod-k@nb@n-thund3r-s3cr3t-k3y-change-this-in-production!"
  DB_USER: "postgres"
  DB_PASSWORD: "securek8spostgrespassword123!"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "securek8spostgrespassword123!"
