# Generated by Django 6.0 on 2026-01-04 11:25

import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("columns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, "Task title cannot be empty."
                            ),
                            django.core.validators.MaxLengthValidator(
                                200, "Task title cannot exceed 200 characters."
                            ),
                            core.validators.validate_no_special_chars,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=2000,
                        validators=[
                            django.core.validators.MaxLengthValidator(
                                2000, "Description cannot exceed 2000 characters."
                            )
                        ],
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Position cannot be negative."
                            )
                        ],
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="columns.column",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "indexes": [
                    models.Index(
                        fields=["column", "position"],
                        name="tasks_task_column__1503b1_idx",
                    ),
                    models.Index(
                        fields=["column", "is_archived"],
                        name="tasks_task_column__223350_idx",
                    ),
                    models.Index(
                        fields=["due_date"], name="tasks_task_due_dat_bce847_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="tasks_task_priorit_a900d4_idx"
                    ),
                ],
            },
        ),
    ]
